### ISSUE TITLE
[HOW TO CONTRIBUTE] Project target and management

### ISSUE THREAD

**Issue by Eomm** [fastify/website#32]
Hi, 
If you are reading this, you want to contribute to the new Fastify website: thank you!
This message explains all you need to know to join.

## Useful links

- Project status: https://github.com/orgs/fastify/projects/5/views/1
- New website preview: https://fastify.github.io/website-next/

## Contribute

If you want to contribute to this project, you can:

- write a comment on an open issue to be assigned to it
- open an issue with your suggestions

### How to contribute

This repository follows the Fastify organization [CONTRIBUTING](https://github.com/fastify/fastify/blob/main/CONTRIBUTING.md) and [GOVERNANCE](https://github.com/fastify/fastify/blob/main/GOVERNANCE.md) statements.
 
As a reminder: **before working on an issue, be sure that**:

- the issue is assigned to your account: wait for an admin reply
- the issue is clear to you: for any question you can drop a comment

To submit valuable changes to the project, you need to fork this repository and submit your code through a Pull Request. Here the step-by-step guides:

- [How to fork](https://docs.github.com/en/get-started/quickstart/fork-a-repo)
- [How to submit a Pull Request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)

## Project target

The target of this project is to redo the Fastify website: https://www.fastify.io/
Migrating to a new tech stack and new processes let the Fastify community contribute more easily to the documentation to let the Fastify web framework grow even more.

This journey was started by @Xhale1 and @luisorbaiceta, and all the credits till commit https://github.com/fastify/website-next/commit/3341dd3131a01d7a8e1d3246c8ccb88f1ba9a88b and the work to sponsor this new project goes to them.

### Tech Stack

The new website will be implemented with [Docusaurus](https://docusaurus.io/). It means that this project includes these topics:

- JSX
- bash scripting
- GitHub Action automation
- markdown manipulation

I'm not an expert on these topics. I'm just a "documentation reader" and a "pragmatic problem solver", so do not expect a TODO-LIST during a PR review, but a collaborative discussion 🤝 

### Project Boundaries

We can't just delete the old website and create a new one 😄 We must abide by these constraints:

1. we must ship fastify with the latest docs. Ref: https://github.com/fastify/fastify/tree/main/docs
2. we must deal with the old website links (eg: redirect)
3. a fastify contributor must update the docs on the main repo `fastify/fastify` (not on this repository)
1. we can't include any doc changes to fastify `<=3`

### Nice to have

**TRACKING PROJECT:** https://github.com/orgs/fastify/projects/7

These features are not in the scope of _this specific project_ - but we will try to implement the required features while keeping in mind the following list:

- [ ] New `Getting started` introduction
- [ ] internationalization
   - [ ] Korean https://github.com/fastify/docs-korean
   - [ ] Chinese https://github.com/fastify/docs-chinese
   - [ ] Portuguese https://github.com/fastify/docs-portuguese
- [ ] Migrate the blog from `https://medium.com/@fastifyjs` to this new website
- [ ] Helper: the user can search across GitHub issues

For sure, we are going to do them in a follow-up project at least 💯 

----

PS: if the issue you are looking at has an empty description, it means that I'm still writing down the requirements, be patient and, meanwhile, fork the repository and start playing with it.. does it work in your local environment?

```[tasklist]
### Tasks
- [x] add a website-metalsmith disclaimer (https://github.com/fastify/website/pull/412)
- [x] rename the `fastify/website` repository to website-metalsmith and archive it
- [x] rename this repository to website (it requires a PR to update some links and reference)
```

**Comment by HassanBahati** [comment]
thank you @Eomm for this project breakdown.

**Comment by jonnydgreen** [comment]
Thanks for the breakdown @Eomm , I'll take a look at some issues I can help out with

**Comment by AugustinMauroy** [comment]
Why do you thinks about an Contributing.md ?

**Comment by Eomm** [comment]
Go for it!

**Comment by Xhale1** [comment]
It's amazing to see this repo get the attention it deserves! I'll try to help out where I can (to which, I'm sorry for not carrying it over the finish line the first time around).

**Comment by mcollina** [comment]
I would recommend we scrap i18n from the plan.

**Comment by Eomm** [comment]
@mcollina I think we are good to start the `fastify.dev` domain redirect to this project.

I would use this setting tho:

![image](https://github.com/fastify/website-next/assets/11404065/08620220-46f9-4362-a468-9c6459052aa4)

Docs: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site

I would propose these steps:

- [ ] make this website available at `fastify.dev`
- [ ] rename the https://github.com/fastify/website repository to `website-metalsmith`
- [ ] add a `website-metalsmith` disclaimer
- [ ] archive the `website-metalsmith` repo
- [ ] rename this repository to `website`

**Comment by mcollina** [comment]
I agree. I'm still trying to get access to fastify.dev. Sigh.

**Comment by Eomm** [comment]
fastify.dev is online

@luisorbaiceta could you finalize this PR: https://github.com/fastify/website-next/pull/97 ?

Then I will proceed by archiving the old website!

**Comment by Eomm** [comment]
Updated the first post https://github.com/fastify/website-next/issues/32#issue-1506897724 with the task list.

**Comment by Eomm** [comment]
Renamed the old repo to https://github.com/fastify/website-metalsmith
I will archive it whenever I will upgrade this repository to `website`

@mcollina could we switch the `fastify.io` domain?

**Comment by mcollina** [comment]
that was done
